# radius constants shamelessly stolen from python dpkt radius module
# http://code.google.com/p/dpkt/source/browse/trunk/dpkt/radius.py
#
# Codes
RADIUS_ACCESS_REQUEST   = 1
RADIUS_ACCESS_ACCEPT    = 2
RADIUS_ACCESS_REJECT    = 3
RADIUS_ACCT_REQUEST     = 4
RADIUS_ACCT_RESPONSE    = 5
RADIUS_ACCT_STATUS      = 6
RADIUS_ACCESS_CHALLENGE = 11

VALID_RADIUS_CODES = [1,2,3,4,5,6,11]

# Attributes
RADIUS_USER_NAME                = 1
RADIUS_USER_PASSWORD            = 2
RADIUS_CHAP_PASSWORD            = 3
RADIUS_NAS_IP_ADDR              = 4
RADIUS_NAS_PORT                 = 5
RADIUS_SERVICE_TYPE             = 6
RADIUS_FRAMED_PROTOCOL          = 7
RADIUS_FRAMED_IP_ADDR           = 8
RADIUS_FRAMED_IP_NETMASK        = 9
RADIUS_FRAMED_ROUTING           = 10
RADIUS_FILTER_ID                = 11
RADIUS_FRAMED_MTU               = 12
RADIUS_FRAMED_COMPRESSION       = 13
RADIUS_LOGIN_IP_HOST            = 14
RADIUS_LOGIN_SERVICE            = 15
RADIUS_LOGIN_TCP_PORT           = 16

# unassigned
RADIUS_REPLY_MESSAGE            = 18
RADIUS_CALLBACK_NUMBER          = 19
RADIUS_CALLBACK_ID              = 20

# unassigned
RADIUS_FRAMED_ROUTE             = 22
RADIUS_FRAMED_IPX_NETWORK       = 23
RADIUS_STATE                    = 24
RADIUS_CLASS                    = 25
RADIUS_VENDOR_SPECIFIC          = 26
RADIUS_SESSION_TIMEOUT          = 27
RADIUS_IDLE_TIMEOUT             = 28
RADIUS_TERMINATION_ACTION       = 29
RADIUS_CALLED_STATION_ID        = 30
RADIUS_CALLING_STATION_ID       = 31
RADIUS_NAS_ID                   = 32
RADIUS_PROXY_STATE              = 33
RADIUS_LOGIN_LAT_SERVICE        = 34
RADIUS_LOGIN_LAT_NODE           = 35
RADIUS_LOGIN_LAT_GROUP          = 36
RADIUS_FRAMED_ATALK_LINK        = 37
RADIUS_FRAMED_ATALK_NETWORK     = 38
RADIUS_FRAMED_ATALK_ZONE        = 39

# 40-59 reserved for accounting
RADIUS_CHAP_CHALLENGE           = 60
RADIUS_NAS_PORT_TYPE            = 61
RADIUS_PORT_LIMIT               = 62
RADIUS_LOGIN_LAT_PORT           = 63

VALID_RADIUS_ATTRIBUTES = [1,2,3,4,56,7,8,9,10,11,12,13,14,15,16,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,60,61,62,63]


#various maxima/minima
MAX_ID = 255
MAX_CODE = 255

MAX_ATTRIBUTE_LENGTH = 253
MAX_ATTRIBUTE_STRING_LENGTH = 253
MAX_ATTRIBUTE_NUMBER_LENGTH = 32
MAX_SECRET_LENGTH = 63
MAX_AUTHENTICATOR_LENGTH = 16
MAX_PACKET_SIZE = 4096

